const fs = require('fs');
const path = require('path');
const childProcess = require('child_process');

const projectRoot = path.join(__dirname, '..');
const compiledRoot = path.join(projectRoot, 'dest', 'lua');
const panelFixtureRoot = path.join(__dirname, 'fixtures', 'panels');
const generatedPanelFixtures = path.join(projectRoot, 'dest', 'test', 'panel_fixtures.lua');

function luaString(value) {
	return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t')}"`;
}

function toLua(value) {
	if (value === null || value === undefined) return 'nil';
	if (typeof value === 'boolean') return value ? 'true' : 'false';
	if (typeof value === 'number') {
		if (!Number.isFinite(value)) throw new Error('Panel fixtures cannot contain non-finite numbers');
		return String(value);
	}
	if (typeof value === 'string') return luaString(value);
	if (Array.isArray(value)) return `{${value.map(toLua).join(',')}}`;
	if (typeof value === 'object') {
		return `{${Object.keys(value).sort().map((key) =>
			`[${luaString(key)}]=${toLua(value[key])}`).join(',')}}`;
	}
	throw new Error(`Unsupported panel fixture value: ${typeof value}`);
}

function compilePanelFixtures() {
	const manifestNames = fs.readdirSync(panelFixtureRoot)
		.filter((name) => name.endsWith('.fixture.json'))
		.sort();
	const fixtures = manifestNames.map((manifestName) => {
		const manifestPath = path.join(panelFixtureRoot, manifestName);
		const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
		if (!manifest.name || !manifest.panel || typeof manifest.legacy !== 'boolean' ||
			!Array.isArray(manifest.tests) || !manifest.tests.length) {
			throw new Error(`${manifestName}: name, panel, legacy, and a non-empty tests array are required`);
		}
		for (const [index, testCase] of manifest.tests.entries()) {
			if (!testCase.name || !testCase.expected || !Array.isArray(testCase.traces)) {
				throw new Error(`${manifestName}: tests[${index}] requires name, traces, and expected`);
			}
		}
		const panelPath = path.resolve(panelFixtureRoot, manifest.panel);
		if (path.dirname(panelPath) !== path.resolve(panelFixtureRoot)) {
			throw new Error(`${manifestName}: panel must be beside its fixture manifest`);
		}
		return {
			name: manifest.name,
			source: path.relative(projectRoot, panelPath),
			legacy: manifest.legacy === true,
			topologyRevision: manifest.topologyRevision || 1,
			tests: manifest.tests,
			panel: JSON.parse(fs.readFileSync(panelPath, 'utf8')),
		};
	});
	fs.mkdirSync(path.dirname(generatedPanelFixtures), { recursive: true });
	fs.writeFileSync(generatedPanelFixtures,
		`-- Generated by tools/sanity.js from tools/fixtures/panels.\nreturn ${toLua(fixtures)}\n`);
	return path.relative(projectRoot, generatedPanelFixtures);
}

const contractTests = [
	['rendering', 'tools/tests/surface.lua'],
	['lifecycle', 'tools/tests/canvas_runtime.lua'],
	['lifecycle', 'tools/tests/pillar_controller.lua'],
	['trace', 'tools/tests/pathfinder.lua'],
	['trace', 'tools/tests/determinism.lua', '25000', '79225'],
	['trace', 'tools/tests/determinism.lua', '25000', '19088743'],
	['rendering', 'tools/tests/presentation.lua'],
	['solver', 'tools/tests/solution.lua'],
	['solver', 'tools/tests/panel_fixtures.lua'],
	['persistence', 'tools/tests/paneldata.lua'],
	['diagnostics', 'tools/tests/debug.lua'],
	['persistence', 'tools/tests/editor_document.lua'],
	['persistence', 'tools/tests/editor_store.lua'],
	['wire/lifecycle', 'tools/tests/panel_sync.lua'],
	['rendering', 'tools/tests/rtpool.lua'],
];
const luaTests = contractTests.map(([, ...test]) => test);
const luaJitTests = luaTests.filter((test) => !(
	test[0] === 'tools/tests/determinism.lua' || test[0] === 'tools/tests/canvas_runtime.lua'
));

function runLuaTest(test, runtime, fixtureModule) {
	const [relativePath, ...args] = test;
	const resolvedArgs = relativePath === 'tools/tests/panel_fixtures.lua' ? [fixtureModule] : args;
	const result = childProcess.spawnSync(runtime, [relativePath, ...resolvedArgs], {
		cwd: projectRoot,
		encoding: 'utf8',
	});
	if (result.stdout) process.stdout.write(`${runtime} ${relativePath}: ${result.stdout}`);
	if (result.status !== 0) {
		if (result.stderr) process.stderr.write(result.stderr);
		throw new Error(`${runtime} test failed: ${relativePath}`);
	}
}

function run() {
	if (!fs.existsSync(compiledRoot)) {
		throw new Error(`Compiled Lua directory is missing: ${path.relative(projectRoot, compiledRoot)}`);
	}

	let fixtureModule;
	try {
		fixtureModule = compilePanelFixtures();
	} catch (error) {
		throw new Error(`Panel fixture compilation failed: ${error.message}`);
	}
	for (const test of luaTests) runLuaTest(test, 'lua', fixtureModule);
	if (childProcess.spawnSync('luajit', ['-v'], { stdio: 'ignore' }).status === 0) {
		for (const test of luaJitTests) runLuaTest(test, 'luajit', fixtureModule);
	}
}

try {
	run();
} catch (error) {
	console.error(error.message);
	process.exitCode = 1;
}
